# Generated by Django 5.1.6 on 2025-04-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='promobanner',
            name='end_date',
            field=models.DateField(blank=True, help_text='Leave blank for no end restriction', null=True),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='start_date',
            field=models.DateField(blank=True, help_text='Leave blank for no start restriction', null=True),
        ),
    ]
