# Generated by Django 5.1.6 on 2025-04-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_promobanner_end_date_promobanner_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='promobanner',
            name='button_style',
            field=models.CharField(choices=[('btn-primary', 'Blue'), ('btn-success', 'Green'), ('btn-danger', 'Red'), ('btn-warning', 'Yellow'), ('btn-info', 'Light Blue'), ('btn-dark', 'Dark'), ('btn-light', 'Light'), ('btn-outline-primary', 'Outlined Blue'), ('btn-outline-success', 'Outlined Green'), ('btn-outline-danger', 'Outlined Red')], default='btn-primary', max_length=20),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='caption_position',
            field=models.CharField(choices=[('center', 'Center'), ('left', 'Left'), ('right', 'Right')], default='center', max_length=10),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='overlay_opacity',
            field=models.FloatField(default=0.4, help_text='Background opacity for caption (0-1)'),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='text_color',
            field=models.CharField(choices=[('text-white', 'White'), ('text-dark', 'Dark'), ('text-primary', 'Blue'), ('text-success', 'Green'), ('text-danger', 'Red'), ('text-warning', 'Yellow')], default='text-white', max_length=20),
        ),
    ]
