# Generated by Django 5.1.6 on 2025-04-03 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_userprofile_wishlist_and_more'),
    ]

    operations = [
    ]
