# Generated by Django 5.1.6 on 2025-04-03 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20250403_1721'),
    ]

    operations = [
    ]
