# Generated by Django 5.1.6 on 2025-04-04 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_userprofile_wishlist'),
        ('store', '0014_auto_20250403_1723'),
    ]

    operations = [
    ]
