# Generated by Django 5.1.6 on 2025-04-04 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_fix_wishlist_removal'),
        ('store', '0016_voucher_cart_voucher_order_fields'),
    ]

    operations = [
    ]
