# Generated by Django 5.1.6 on 2025-04-04 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_merge_20250404_1050'),
        ('store', '0017_merge_wishlist_voucher_fields'),
    ]

    operations = [
    ]
