# Generated by Django 5.1.6 on 2025-04-04 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_cart_order_voucher_fields'),
        ('store', '0020_add_voucher_relationships'),
    ]

    operations = [
    ]
