# Generated by Django 5.1.6 on 2025-04-04 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_merge_20250404_1057'),
        ('store', '0022_final_wishlist_removal'),
    ]

    operations = [
    ]
