# Generated by Django 5.1.6 on 2025-04-04 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_notification_type_reference_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='voucher',
        ),
        migrations.RemoveField(
            model_name='order',
            name='notes',
        ),
    ]
