# Generated by Django 5.1.6 on 2025-04-04 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_remove_cart_voucher_remove_order_notes'),
    ]

    operations = [
    ]
