# Generated by Django 5.1.6 on 2025-04-04 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_uservoucher'),
        ('store', '0033_add_phone_number_to_order'),
    ]

    operations = [
    ]
