# Generated by Django 5.1.6 on 2025-04-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_add_subtotal_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='voucher_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
