# Generated by Django 5.1.6 on 2025-04-04 15:48

from django.db import migrations

# It's generally recommended to provide a reverse SQL operation
# to make the migration reversible, but in this case, we are
# correcting a schema inconsistency, so adding the column back
# might not be desired if we roll back.
# If needed, the reverse operation would be:
# reverse_sql = "ALTER TABLE store_order ADD COLUMN notes longtext;"

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_add_total_price_to_order'),
    ]

    operations = [
        # Use RunSQL to bypass Django state checks and directly remove the column
        migrations.RunSQL(
            sql="ALTER TABLE store_order DROP COLUMN notes;",
            reverse_sql=migrations.RunSQL.noop # Or provide reverse SQL if needed
        ),
    ]
