# Generated by Django 5.1.6 on 2025-04-04 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='active_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='store.uservoucher'),
        ),
        migrations.AlterField(
            model_name='order',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.uservoucher'),
        ),
    ]
