# Generated by Django 5.1.6 on 2025-04-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_voucher_voucher_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservoucher',
            name='message',
            field=models.CharField(blank=True, help_text='Personalized message to send to the user', max_length=255, null=True),
        ),
    ]
