# Generated by Django 5.1.6 on 2025-04-06 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_fix_package_models'),
    ]

    operations = [
    ]
