# Generated by Django 5.1.6 on 2025-04-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_merge_20250406_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagerating',
            name='staff_reviewed',
            field=models.BooleanField(default=False, help_text='Has this rating been reviewed by staff'),
        ),
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='product',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productrating',
            name='staff_reviewed',
            field=models.BooleanField(default=False, help_text='Has this rating been reviewed by staff'),
        ),
    ]
