# Generated by Django 5.1.6 on 2025-04-07 13:46

from django.db import migrations


class Migration(migrations.Migration):
    """
    This migration fixes the conflict with migration 0047.
    It acts as if the changes from 0047 have already been applied.
    """

    dependencies = [
        ('store', '0047_packagerating_staff_reviewed_product_average_rating_and_more'),
    ]

    operations = [
        # No operations needed - the fields already exist in the database
        # This migration just updates Django's migration state tracking
    ]
