@echo off
echo Starting Daphne WebSocket server on port 9000...
call venv\Scripts\activate.bat
echo Setting DJANGO_SETTINGS_MODULE environment variable...
set DJANGO_SETTINGS_MODULE=ecommerce_project.settings
echo Starting Daphne server...
daphne -b 0.0.0.0 -p 9000 --verbosity 3 --access-log - ecommerce_project.asgi:application 