# Generated by Django 5.1.6 on 2025-04-13 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='E-Commerce Admin', max_length=100)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='admin/logos/')),
                ('primary_color', models.CharField(default='#3498db', max_length=20)),
                ('secondary_color', models.CharField(default='#2ecc71', max_length=20)),
                ('enable_dark_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Admin Configuration',
                'verbose_name_plural': 'Admin Configurations',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('minimum_spend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('color_class', models.CharField(default='primary', help_text='Bootstrap color class (primary, secondary, success, etc.)', max_length=20)),
                ('icon', models.CharField(default='fas fa-medal', max_length=50)),
                ('badge_color', models.CharField(default='#3498db', max_length=20)),
                ('tier_level', models.PositiveIntegerField(default=1, help_text='Used for sorting tiers')),
                ('benefits', models.TextField(blank=True, help_text='Comma-separated list of benefits')),
                ('tier_benefits', models.TextField(blank=True, help_text='List benefits users receive at this tier')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage discount for this tier (0-100)', max_digits=5)),
                ('voucher_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount of voucher issued when customer reaches this tier', max_digits=8)),
                ('is_active', models.BooleanField(default=True, help_text='Only active tiers are assigned to customers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loyalty Tier',
                'verbose_name_plural': 'Loyalty Tiers',
                'ordering': ['minimum_spend'],
            },
        ),
        migrations.CreateModel(
            name='CustomerLoyalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('points', models.IntegerField(default=0)),
                ('anniversary_date', models.DateField(blank=True, null=True)),
                ('last_anniversary_reward', models.DateField(blank=True, null=True)),
                ('tier_updated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty', to=settings.AUTH_USER_MODEL)),
                ('current_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_admin.loyaltytier')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(choices=[('tier', 'Tier Upgrade'), ('anniversary', 'Anniversary'), ('manual', 'Manually Created')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_admin.loyaltytier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_vouchers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
